name: ml-ad
channels:
  - defaults
dependencies:
  - matplotlib
  - tensorflow
  - python-graphviz
  - pydot
  - xgboost
  - jinja2
  - python=3.7
  - ipython_genutils
  - seaborn
  - keras
  - pandas
  - ipykernel
