name: ml-ad
channels:
  - defaults
dependencies:
  - matplotlib
  - tensorflow=2.0.0
  - python-graphviz
  - pydot
  - xgboost=1.3.3
  - jinja2
  - python=3.7
  - ipython_genutils
  - seaborn
  - keras=2.3.1
  - pandas=1.2.4
  - ipykernel
